version: '3'

services:
  nginx:
    container_name: nginx
    build: ./nginx
    depends_on:
      - php
    networks:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./data/www:/var/www/html
      - ./nginx/default.${APP_ENV}.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.${APP_ENV}.conf:/etc/nginx/nginx.conf

  php:
    container_name: php
    build: ./php72
    networks:
      - backend
    volumes:
      - ./data/www:/var/www/html
      - ./php72/php.${APP_ENV}.ini:/usr/local/etc/php/php.ini

networks:
  backend:
