version: '3'

services:
  nginx:
    container_name: nginx
    build: ./nginx
    depends_on:
      - php
    networks:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./data/www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    container_name: php
    build: ./php72
    networks:
      - backend
    volumes:
      - ./data/www:/var/www/html

networks:
  backend:
